language: python

python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"

install:
  - pip install --upgrade pip
  - pip install pytest
  - pip install --editable .

# Use travis docker infrastructure for greater speed
sudo: false

script: make test

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
