language: python

# Use travis docker infrastructure for greater speed
sudo: false

cache:
  directories:
  - cldr

matrix:
  include:
    - os: linux
      python: 2.6
    - os: linux
      python: 2.7
    - os: linux
      python: pypy
    - os: linux
      python: 3.3
    - os: linux
      python: 3.4
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=2.6.6
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=2.7.10
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=pypy-2.6.0
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=3.3.6
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin
    - os: osx
      language: generic
      env:
      - PYTHON_VERSION=3.4.3
      - PYENV_ROOT=~/.pyenv
      - PATH=$PYENV_ROOT/shims:$PATH:$PYENV_ROOT/bin

install:
  - bash .ci/deps.${TRAVIS_OS_NAME}.sh
  - pip install --upgrade pip
  - pip install pytest pytest-cov
  - pip install --editable .

script:
  - make test-cov
  - bash .ci/deploy.${TRAVIS_OS_NAME}.sh

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
